// Mocks generated by Mockito 5.4.4 from annotations
// in popular_people/test/features/person_details/presentation/view_model/cubit/person_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:popular_people/core/handlers/error_handler/failure.dart' as _i5;
import 'package:popular_people/features/person_details/data/models/pereson_images_model.dart'
    as _i7;
import 'package:popular_people/features/person_details/data/models/person_details_model.dart'
    as _i6;
import 'package:popular_people/features/person_details/data/repo/person_details_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonDetailsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonDetailsRepo extends _i1.Mock implements _i3.PersonDetailsRepo {
  MockPersonDetailsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PersonDetailsModel>> getPersonDetails(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonDetails,
          [],
          {#id: id},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PersonDetailsModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.PersonDetailsModel>(
          this,
          Invocation.method(
            #getPersonDetails,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PersonDetailsModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Profiles>>> getPersonImages(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonImages,
          [],
          {#id: id},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.Profiles>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Profiles>>(
          this,
          Invocation.method(
            #getPersonImages,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Profiles>>>);
}
